MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/resnest269-0cc87c48.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'resnest269'
  NO_MARGIN: True
  DEVICE_ID: ('0')

INPUT:
  SIZE_TRAIN: [320, 320]
  SIZE_TEST: [320, 320]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('dm')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 16
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 40
  BASE_LR: 0.01
  IMS_PER_BATCH: 48
  STEPS: [30]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10

TEST:
  EVAL: True
  IMS_PER_BATCH: 100
  RE_RANKING: False
  RE_RANKING_TRACK: False
  WEIGHT: '/data/final/resnest269_320/16/resnest269_40.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: '/data/final/resnest269_320/16'


